development:
  clients:
    default:
      uri: mongodb://localhost:27017/open_countries_development
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGO_HOST', 'mongodb://localhost:27017/open_countries_test') %>
      options:
        server_selection_timeout: 5
