development:
  clients:
    default:
      database: open_countries_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: open_countries_test
      hosts:
        - localhost:27017
